spring:
  datasource:
    url: "jdbc:h2:mem:christmas;MODE=MYSQL"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 5000

jwt:
  token:
    header: Authorization
    issuer: christmas
    client-secret: fewge1r3we2y43qrgjytk45w612yh
    expiry-seconds: 0
